#!/usr/bin/env python3
"""
Dictum Project Builder — builds an entire multi-file .dict project to C/C++.

Given a workspace directory (or a dictum.project.json manifest), it:
  1. Discovers all .dict files
  2. Topologically sorts them (modules before programs that use them)
  3. Transpiles each file
  4. Generates .h stub headers for every module so cross-file #includes resolve
  5. Writes all .c/.cpp files, headers, and a unified Makefile
  6. Reports any errors with file + line context

Usage:
  python3 project_builder.py <workspace_dir> [--backend c|cpp] [--out <build_dir>]
"""

from __future__ import annotations
import os, sys, re, json, argparse
from pathlib import Path
from typing import Dict, List, Set, Tuple, Optional

# Same proven pattern as dictumc_cli.py (which works correctly standalone):
# insert the extension root — the parent of compiler/ — onto sys.path, then
# import dictumc.transpiler as a genuine absolute package import. dictumc/ has
# an __init__.py, so its own internal relative imports (e.g. transpiler.py's
# `from .lexer import ...`) resolve correctly once dictumc is imported as a
# package this way.
#
# The previous attempt added compiler/ itself to sys.path and fell back to
# the root-level compiler/transpiler.py on ImportError — but that file has
# the identical internal `from .lexer import ...` relative import, which
# fails the same way when transpiler.py is loaded as a bare top-level module
# rather than as part of a package. The fallback target was broken in the
# same way as the thing it was falling back from.
_EXT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _EXT_ROOT not in sys.path:
    sys.path.insert(0, _EXT_ROOT)

try:
    # Preferred: relative import, works when project_builder.py is itself
    # imported as part of the dictumc package (e.g. `from dictumc import
    # project_builder`, which is how compiler/dictumc/project_builder.py
    # would be reached if/when it's added there).
    from .transpiler import Transpiler, StdlibTranspiler
    from .validator import ValidationError
except ImportError:
    # Standalone script execution (`python3 project_builder.py ...`, which is
    # how the VS Code extension's buildProject command actually invokes this
    # file). dictumc has an __init__.py, so this resolves correctly.
    from dictumc.transpiler import Transpiler, StdlibTranspiler
    from dictumc.validator import ValidationError


# ── Type mapping: Dictum → C ───────────────────────────────────────────────────
DICTUM_TYPE_TO_C = {
    'whole number':    'int32_t',
    'decimal number':  'double',
    'text':            'const char*',
    'truth value':     'bool',
    'count':           'size_t',
    'bytes':           'uint8_t*',
    'nothing':         'void',
}

def dictum_type_to_c(dt: str) -> str:
    return DICTUM_TYPE_TO_C.get(dt.strip(), 'int32_t')


# ── Parse a .dict file for dependency info (fast, no full parse) ───────────────
def parse_deps(source: str, filepath: str) -> Dict:
    """
    Lightweight parser: extracts module/program names and their `use` dependencies.
    Returns { 'modules': [...], 'programs': [...], 'uses': [...], 'shapes': [...], 'actions': [...] }
    """
    modules, programs, uses, shapes, actions = [], [], [], [], []
    for line in source.splitlines():
        m = re.match(r'^\s*module\s+(\w+)\s*:', line)
        if m: modules.append(m.group(1))
        m = re.match(r'^\s*program\s+(\w+)\s*:', line)
        if m: programs.append(m.group(1))
        m = re.match(r'^\s*use\s+(\w+)', line)
        if m: uses.append(m.group(1))
        m = re.match(r'^\s*shape\s+(\w+)\s+holds\s*:', line)
        if m: shapes.append(m.group(1))
        m = re.match(r'^\s*action\s+(\w+)\s+(?:takes|produces)', line)
        if m: actions.append(m.group(1))
    return {'modules': modules, 'programs': programs, 'uses': uses,
            'shapes': shapes, 'actions': actions, 'file': filepath}


# ── Generate a .h header from transpiled C source ─────────────────────────────
def generate_header(module_name: str, c_source: str, dict_source: str) -> str:
    """
    Extract function declarations from transpiled C, generate a proper header.
    Includes dictum_types.h so cross-module shape references resolve.
    """
    guard = f"DICTUM_{module_name.upper()}_H"
    lines = [
        f"/* Auto-generated by dictumc project builder */",
        f"/* Module: {module_name} */",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f"#include <stdint.h>",
        f"#include <stdbool.h>",
        f"#include <stdlib.h>",
        f'#include "dictum_types.h"',   # brings in all cross-project shapes
        f"",
    ]

    # Extract struct definitions (shapes)
    struct_blocks = re.findall(r'(typedef\s+struct\s+\w+\s*\{[^}]+\}\s*\w+\s*;)', c_source, re.DOTALL)
    for sb in struct_blocks:
        lines.append(sb.strip())
        lines.append("")

    # Extract function declarations (strip body, add semicolon)
    # Pattern: returntype funcname(params) {
    fn_pattern = re.compile(
        r'^((?:int32_t|double|bool|void|const char\*|size_t|uint8_t\*|uint64_t|int64_t)\s+'
        r'\w+\s*\([^)]*\))\s*\{',
        re.MULTILINE
    )
    for m in fn_pattern.finditer(c_source):
        lines.append(f"{m.group(1)};")

    lines += ["", f"#endif /* {guard} */", ""]
    return "\n".join(lines)


# ── Topological sort ──────────────────────────────────────────────────────────
def topo_sort(file_info: List[Dict]) -> List[Dict]:
    """Sort files so modules come before programs that use them."""
    # Build module-name → file index
    mod_to_idx: Dict[str, int] = {}
    for i, fi in enumerate(file_info):
        for m in fi['modules']:
            mod_to_idx[m] = i

    # Build adjacency (file uses file)
    n = len(file_info)
    adj: List[Set[int]] = [set() for _ in range(n)]
    for i, fi in enumerate(file_info):
        for used in fi['uses']:
            if used in mod_to_idx:
                adj[i].add(mod_to_idx[used])  # i depends on mod_to_idx[used]

    # Kahn's algorithm
    in_degree = [0] * n
    for i in range(n):
        for j in adj[i]:
            in_degree[j] += 0  # adj[i] = dependencies of i, not reverse
    # Build reverse: who depends on me
    rev: List[Set[int]] = [set() for _ in range(n)]
    for i in range(n):
        for dep in adj[i]:
            rev[dep].add(i)

    in_deg = [len(adj[i]) for i in range(n)]
    queue = [i for i in range(n) if in_deg[i] == 0]
    order = []
    while queue:
        node = queue.pop(0)
        order.append(node)
        for dependent in rev[node]:
            in_deg[dependent] -= 1
            if in_deg[dependent] == 0:
                queue.append(dependent)

    if len(order) != n:
        # Cycle detected — just return original order
        return file_info
    return [file_info[i] for i in order]


# ── Generate unified Makefile ─────────────────────────────────────────────────
def generate_makefile(
    file_info: List[Dict],
    c_files: List[str],
    build_dir: str,
    backend: str,
    cpp_standard: int,
    ldflags: Optional[Set[str]] = None,
) -> str:
    programs = []
    for fi in file_info:
        programs.extend(fi['programs'])

    ext = '.c' if backend == 'c' else '.cpp'
    compiler = 'gcc' if backend == 'c' else 'g++'
    std_flag = '' if backend == 'c' else f'-std=c++{cpp_standard} '
    asan_flag = '-fsanitize=address -fno-omit-frame-pointer '

    obj_list = ' '.join(
        os.path.splitext(os.path.basename(f))[0] + '.o'
        for f in c_files
    )
    prog_name = programs[0].lower() if programs else 'dictum_out'

    # FIX (link-flag plumbing bug): this used to hardcode "-lm" no matter
    # what any file in the project used, so any project touching
    # Mutex/Thread/Semaphore (-lpthread), Tls (-lssl -lcrypto), Shm/Timer
    # (-lrt), or a blessed library's #[link "x"] directive would compile
    # every file successfully and then fail at the final link step with
    # undefined references. `ldflags` is aggregated across every file's
    # real get_ldflags() result by the caller.
    ldflags_sorted = sorted(ldflags) if ldflags else ['-lm']
    # Keep -lm first for readability/stability, rest alphabetical.
    if '-lm' in ldflags_sorted:
        ldflags_sorted.remove('-lm')
        ldflags_sorted.insert(0, '-lm')
    ldflags_str = ' '.join(ldflags_sorted)

    lines = [
        f"# Auto-generated by dictumc project builder",
        f"# Rebuild with: make",
        f"",
        f"CC       = {compiler}",
        f"CFLAGS   = {std_flag}-Wall -Wextra -O2 -I.",
        f"CFLAGS_D = {std_flag}{asan_flag}-Wall -Wextra -O1 -g -I.  # debug+asan",
        f"LDFLAGS  = {ldflags_str}",
        f"SRCS     = {' '.join(os.path.basename(f) for f in c_files)}",
        f"OBJS     = {obj_list}",
        f"TARGET   = {prog_name}",
        f"",
        f"all: $(TARGET)",
        f"",
        f"$(TARGET): $(OBJS)",
        f"\t$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)",
        f"",
        f"%.o: %{ext}",
        f"\t$(CC) $(CFLAGS) -c -o $@ $<",
        f"",
        f"debug: $(SRCS)",
        f"\t$(CC) $(CFLAGS_D) -o $(TARGET)_debug $^ $(LDFLAGS)",
        f"",
        f"clean:",
        f"\trm -f $(OBJS) $(TARGET) $(TARGET)_debug",
        f"",
        f".PHONY: all debug clean",
    ]
    return "\n".join(lines)


# ── Project manifest ──────────────────────────────────────────────────────────
def load_or_create_manifest(workspace: str) -> Dict:
    manifest_path = os.path.join(workspace, 'dictum.project.json')
    if os.path.exists(manifest_path):
        with open(manifest_path) as f:
            return json.load(f)
    # Auto-discover
    return {
        'name': os.path.basename(workspace),
        'version': '0.1.0',
        'backend': 'c',
        'cpp_standard': 17,
        'entry': None,  # None = auto-detect program files
        'exclude': ['build/', '.git/', 'node_modules/'],
    }


def write_manifest(workspace: str, manifest: Dict):
    path = os.path.join(workspace, 'dictum.project.json')
    with open(path, 'w') as f:
        json.dump(manifest, f, indent=2)
    return path


# ── Main build function ───────────────────────────────────────────────────────
def build_project(
    workspace: str,
    backend: str = 'c',
    cpp_standard: int = 17,
    out_dir: Optional[str] = None,
    verbose: bool = False,
) -> Dict:
    """
    Build all .dict files in workspace to C/C++.
    Returns {'success': bool, 'files': [...], 'errors': [...], 'warnings': [...]}
    """
    workspace = os.path.abspath(workspace)
    manifest  = load_or_create_manifest(workspace)
    backend   = manifest.get('backend', backend)
    cpp_std   = manifest.get('cpp_standard', cpp_standard)
    build_dir = out_dir or os.path.join(workspace, 'build')
    os.makedirs(build_dir, exist_ok=True)

    exclude = manifest.get('exclude', [])
    ext_out = '.c' if backend == 'c' else '.cpp'

    # ── 1. Discover all .dict files ───────────────────────────────────────
    dict_files = []
    for root, dirs, files in os.walk(workspace):
        # Prune excluded dirs
        dirs[:] = [d for d in dirs if not any(
            os.path.join(root, d).startswith(os.path.join(workspace, ex.rstrip('/')))
            for ex in exclude
        )]
        for fname in files:
            if fname.endswith('.dict'):
                dict_files.append(os.path.join(root, fname))

    if not dict_files:
        return {'success': False, 'errors': [f'No .dict files found in {workspace}'], 'files': [], 'warnings': []}

    # ── 2. Parse dependencies ─────────────────────────────────────────────
    file_info = []
    for fp in dict_files:
        with open(fp, encoding='utf-8') as f:
            src = f.read()
        info = parse_deps(src, fp)
        info['source'] = src
        file_info.append(info)

    # ── 3. Topological sort ───────────────────────────────────────────────
    sorted_info = topo_sort(file_info)

    # ── 4. Pre-pass: collect all shape structs into a shared types header ────
    import re as _re
    all_shapes_code: List[str] = []
    shape_header_path = os.path.join(build_dir, 'dictum_types.h')

    for fi in sorted_info:
        if fi['shapes']:
            try:
                t_pre = StdlibTranspiler(source=fi['source'], backend=backend, cpp_standard=cpp_std)
                r_pre = t_pre.run(validate=False)
                # Match: typedef struct { ... } Name;
                structs = _re.findall(
                    r'typedef struct\s*\{[^}]+\}\s*\w+\s*;',
                    r_pre['code'], _re.DOTALL
                )
                all_shapes_code.extend(structs)
            except Exception:
                pass

    # Always write dictum_types.h — module headers include it unconditionally.
    # If no shapes exist it is just an empty guard header.
    type_hdr_lines = [
        '/* dictum_types.h — auto-generated shared type definitions */',
        '#ifndef DICTUM_TYPES_H', '#define DICTUM_TYPES_H',
        '#include <stdint.h>', '#include <stdbool.h>', '#include <stdlib.h>', '',
    ] + ([s.strip() for s in all_shapes_code] if all_shapes_code else []) + ['', '#endif /* DICTUM_TYPES_H */']
    with open(shape_header_path, 'w', encoding='utf-8') as _fh:
        _fh.write('\n'.join(type_hdr_lines))
    # written_files.append(shape_header_path) — added below after list init

    # ── 4b. Transpile each file ───────────────────────────────────────────────
    errors, warnings, written_files = [], [], []
    written_files.append(shape_header_path)  # always present
    generated_headers: Dict[str, str] = {}  # module_name → header path
    all_ldflags: Set[str] = {'-lm'}  # aggregated across every file for the unified Makefile

    for fi in sorted_info:
        fp = fi['file']
        rel = os.path.relpath(fp, workspace)
        if verbose:
            print(f"  compiling {rel}...", file=sys.stderr)

        try:
            # FIX (Problem 0 gap): this was plain Transpiler, so a
            # multi-file project never got STDLIB_ACTION_FAMILIES
            # registration (extend_validator/extend_emitter) at all —
            # File/Json/Http/Net/Mutex/Math/etc. calls in a project build
            # would fail validation outright, a stricter failure mode than
            # the single-file CLI path (which supports `--stdlib`).
            t = StdlibTranspiler(
                source=fi['source'],
                backend=backend,
                cpp_standard=cpp_std,
            )
            result = t.run(validate=True)
        except (SyntaxError, ValidationError) as e:
            errors.append({'file': rel, 'message': str(e), 'line': 0})
            continue
        except Exception as e:
            errors.append({'file': rel, 'message': f'Internal error: {e}', 'line': 0})
            continue

        if result.get('warnings'):
            for w in result['warnings']:
                warnings.append({'file': rel, 'message': str(w)})

        # FIX (link-flag plumbing bug): collect this file's real ldflags
        # (from `use X` modules + #[link ...] directives) so the unified
        # project Makefile generated at the end can actually link — it
        # used to hardcode "-lm" regardless of what any file needed.
        all_ldflags.update(result.get('ldflags') or ['-lm'])

        c_code = result['code']

        # Determine output filename
        base = os.path.splitext(os.path.basename(fp))[0]
        out_path = os.path.join(build_dir, base + ext_out)

        # Strip per-file stdlib includes — Makefile handles linking
        # Keep the code as-is for now (fully self-contained)
        # Include dictum_types.h in files that DON'T define their own shapes
        file_defines_shapes = len(fi['shapes']) > 0
        if all_shapes_code and not file_defines_shapes:
            c_code = '#include "dictum_types.h"\n' + c_code

        # ── Module prefix: rename `action_name` → `ModuleName_action_name` ─
        # The compiler emits unqualified names; the program calls prefixed names.
        # We patch the module .c to match what the program emits.
        for mod_name in fi['modules']:
            for action_name in fi['actions']:
                # Replace function definitions: `int32_t action_name(` → `int32_t ModuleName_action_name(`
                # Use word-boundary to avoid partial replacements
                c_code = _re.sub(
                    r'(?<![A-Za-z0-9_])' + _re.escape(action_name) + r'\s*\(',
                    f'{mod_name}_{action_name}(',
                    c_code
                )

        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(c_code)
        written_files.append(out_path)

        # ── 5. Generate .h header for every module ────────────────────────
        for mod_name in fi['modules']:
            header_content = generate_header(mod_name, c_code, fi['source'])
            h_name = f"dictum_{mod_name.lower()}.h"
            h_path = os.path.join(build_dir, h_name)
            with open(h_path, 'w', encoding='utf-8') as f:
                f.write(header_content)
            generated_headers[mod_name] = h_path
            written_files.append(h_path)
            if verbose:
                print(f"    → {h_name}", file=sys.stderr)

    # ── 6. Generate stub headers referenced but not defined ───────────────
    # e.g. dictum_core.h, dictum_error.h
    for stub_name in ['dictum_core', 'dictum_error']:
        h_path = os.path.join(build_dir, stub_name + '.h')
        if not os.path.exists(h_path):
            with open(h_path, 'w', encoding='utf-8') as f:
                f.write(f"/* {stub_name}.h — auto-generated stub */\n")
                f.write(f"#ifndef {stub_name.upper()}_H\n")
                f.write(f"#define {stub_name.upper()}_H\n")
                f.write(f"#include <stdint.h>\n#include <stdbool.h>\n#include <stdlib.h>\n")
                f.write(f"#endif\n")
            written_files.append(h_path)

    # ── 7. Write Makefile ─────────────────────────────────────────────────
    c_files = [f for f in written_files if f.endswith(ext_out)]
    makefile = generate_makefile(sorted_info, c_files, build_dir, backend, cpp_std, all_ldflags)
    mf_path  = os.path.join(build_dir, 'Makefile')
    with open(mf_path, 'w', encoding='utf-8') as f:
        f.write(makefile)
    written_files.append(mf_path)

    # ── 8. Write/update manifest ──────────────────────────────────────────
    if not os.path.exists(os.path.join(workspace, 'dictum.project.json')):
        write_manifest(workspace, {
            **manifest,
            'backend': backend,
            'cpp_standard': cpp_std,
        })
        written_files.append(os.path.join(workspace, 'dictum.project.json'))

    n_modules  = sum(len(fi['modules'])  for fi in sorted_info)
    n_programs = sum(len(fi['programs']) for fi in sorted_info)

    return {
        'success': len(errors) == 0,
        'files': written_files,
        'errors': errors,
        'warnings': warnings,
        'stats': {
            'dict_files': len(dict_files),
            'modules': n_modules,
            'programs': n_programs,
            'c_files': len(c_files),
            'headers': len(generated_headers),
        }
    }


# ── CLI ───────────────────────────────────────────────────────────────────────
def main():
    p = argparse.ArgumentParser(
        prog='project_builder',
        description='Build a multi-file Dictum project to C/C++',
    )
    p.add_argument('workspace', help='Project directory (contains .dict files)')
    p.add_argument('--backend', choices=['c', 'cpp'], default='c')
    p.add_argument('--cpp-standard', type=int, choices=[17, 20, 23], default=17)
    p.add_argument('--out', default='', help='Output directory (default: <workspace>/build)')
    p.add_argument('--verbose', '-v', action='store_true')
    args = p.parse_args()

    result = build_project(
        workspace=args.workspace,
        backend=args.backend,
        cpp_standard=args.cpp_standard,
        out_dir=args.out or None,
        verbose=args.verbose,
    )

    if result['errors']:
        for e in result['errors']:
            print(f"ERROR [{e['file']}]: {e['message']}", file=sys.stderr)

    if result['warnings']:
        for w in result['warnings']:
            print(f"WARNING [{w['file']}]: {w['message']}", file=sys.stderr)

    s = result['stats']
    print(f"{'✓' if result['success'] else '✗'} "
          f"{s['dict_files']} files → {s['c_files']} C files, "
          f"{s['headers']} headers, Makefile")
    for f in result['files']:
        print(f"  → {f}")

    return 0 if result['success'] else 1


if __name__ == '__main__':
    sys.exit(main())
